spring:
  datasource:
    platform: mariadb
    driverClassName: org.mariadb.jdbc.Driver
    # Fixed in v1.3.3. Doesn't work with mariadb-connector-j v1.3.2 (CONJ-227)
    url: jdbc:mariadb://localhost:32768/DBSales
    # If some of the hosts is down, app won't launch. v1.3.3
    #url: jdbc:mariadb:failover://192.168.33.11:3306,192.168.33.12:3306,192.168.33.13:3306/test?autoReconnect=true
    # Works with mariadb-connector-j v1.3.2
    #url: jdbc:mysql:failover://192.168.33.11:3306/test
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml