# please don't put any local settings to application.yml
server:
  port: 9093

spring:
  datasource:
    platform: mariadb
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/testdb?createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml

kafka.logging.level.root: INFO
kafka.com.education.address: 127.0.0.1:9092
kafka.com.education.topic: test-topic
kafka.com.education.consumer.groupId: defaultGrpId
kafka.com.education.consumer.clientId: defaultClId
kafka.request.timeout.ms: 20000
kafka.bootstrap.servers: http://localhost:9092