version: '3.1'

services:
  hk-kafka:
    image: spotify/kafka
    ports:
      - "2181:2181"
      - "9092:9092"
    hostname: localhost
    container_name: kafka
    environment:
      - "KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181"
      - "ALLOW_PLAINTEXT_LISTENER=yes"
      - "ADVERTISED_HOST=localhost"
      - "ADVERTISED_PORT=9092"
      - "AUTO_CREATE_TOPICS_true"
    depends_on:
      - zookeeper